In [1]:
%%writefile 1.txt
This is a story about cats
our feline pets
cats are furry animals

Overwriting 1.txt


In [2]:
%%writefile 2.txt
This is a story about surfing
catching waves is fun
surfing is a popular water sports

Overwriting 2.txt


In [3]:
vocab = {}
i = 1

with open('1.txt') as f:
    x = f.read().lower().split()
    
for word in x:
    if word in vocab:
        continue
    else:
        vocab[word]=i
        i+=1
        
print(vocab)

{'this': 1, 'is': 2, 'a': 3, 'story': 4, 'about': 5, 'cats': 6, 'our': 7, 'feline': 8, 'pets': 9, 'are': 10, 'furry': 11, 'animals': 12}


In [4]:
with open('2.txt') as f:
    x = f.read().lower().split()
    
for word in x:
    if word in vocab:
        continue
    else:
        vocab[word]=i
        i+=1
        
print(vocab)

{'this': 1, 'is': 2, 'a': 3, 'story': 4, 'about': 5, 'cats': 6, 'our': 7, 'feline': 8, 'pets': 9, 'are': 10, 'furry': 11, 'animals': 12, 'surfing': 13, 'catching': 14, 'waves': 15, 'fun': 16, 'popular': 17, 'water': 18, 'sports': 19}


In [5]:
# create an empty vector with space for rach word in vocabulary
one = ['1.txt']+[0]*len(vocab)
one

['1.txt', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [6]:
# map the frequency of each word in 1.txt to our vector:

with open('1.txt') as f:
    x = f.read().lower().split()
    
for word in x:
    one[vocab[word]]+=1
    
one

['1.txt', 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]

In [7]:
two = ['2.txt']+[0]*len(vocab)

In [8]:
with open('1.txt') as f:
    x = f.read().lower().split()
    
for word in x:
    one[vocab[word]]+=1

In [9]:
print(f'{one}\n{two}')

['1.txt', 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0]
['2.txt', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [10]:
import numpy as np
import pandas as pd

In [11]:
 df = pd.read_csv('../spam.csv',encoding='ISO-8859-1')

In [12]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [13]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x = df['v1']

In [16]:
y = df['v2']

In [17]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.33,random_state=42)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
count_vect = CountVectorizer()

In [20]:
# # fit vectorizer to the data(build vocab,count no of words)
# count_vect.fit(X_train)
# X_train_counts = count_vect.transform(X_train)
# # transform the original text message to vector

X_train_count=count_vect.fit_transform(X_train)

In [21]:
X_train_count

<3733x2 sparse matrix of type '<class 'numpy.int64'>'
	with 3733 stored elements in Compressed Sparse Row format>

In [22]:
X_train.shape #show total messages

(3733,)

In [23]:
from sklearn.feature_extraction.text import TfidfTransformer

In [24]:
tfid_transformer = TfidfTransformer()

In [26]:
X_train_tfidf = tfid_transformer.fit_transform(X_train_count)

In [28]:
X_train_tfidf.shape

(3733, 2)

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [30]:
vectorizer  = TfidfVectorizer()

In [31]:
X_train_tfidf = vectorizer.fit_transform(X_train)

In [35]:
from sklearn.svm import LinearSVC

In [38]:
clf = LinearSVC()

In [39]:
clf.fit(X_train_tfidf,Y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [40]:
from sklearn.pipeline import Pipeline

In [41]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('clf',LinearSVC())])

In [42]:
text_clf.fit(X_train,Y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
               

In [43]:
prediction = text_clf.predict(X_test)

In [44]:
from sklearn.metrics import confusion_matrix,classification_report

In [46]:
print(confusion_matrix(Y_test,prediction))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
