In [1]:
import pandas as pd

In [2]:
npr = pd.read_csv('articles.csv')

In [3]:
npr.head()

author claps  reading_time  \
0        Justin Lee  8.3K            11   
1       Conor Dewey  1.4K             7   
2  William Koehrsen  2.8K            11   
3      Gant Laborde  1.3K             7   
4  Emmanuel Ameisen   935            11   

                                                link  \
0  https://medium.com/swlh/chatbots-were-the-next...   
1  https://towardsdatascience.com/python-for-data...   
2  https://towardsdatascience.com/automated-featu...   
3  https://medium.freecodecamp.org/machine-learni...   
4  https://blog.insightdatascience.com/reinforcem...   

                                               title  \
0  Chatbots were the next big thing: what happene...   
1  Python for Data Science: 8 Concepts You May Ha...   
2  Automated Feature Engineering in Python – Towa...   
3  Machine Learning: how to go from Zero to Hero ...   
4  Reinforcement Learning from scratch – Insight ...   

                                                text  
0  Oh, how the headlines blared:\nChatbots were T...  
1  If you’ve ever found yourself looking up the s...  
2  Machine learning is increasingly moving from h...  
3  If your understanding of A.I. and Machine Lear...  
4  Want to learn about applied Artificial Intelli...

In [4]:
len(npr)

337

In [5]:
npr['text'][4]

'Want to learn about applied Artificial Intelligence from leading practitioners in Silicon Valley, New York, or Toronto? Learn more about the Insight Artificial Intelligence Fellows Program.\nAre you a company working in AI and would like to get involved in the Insight AI Fellows Program? Feel free to get in touch.\nRecently, I gave a talk at the O’Reilly AI conference in Beijing about some of the interesting lessons we’ve learned in the world of NLP. While there, I was lucky enough to attend a tutorial on Deep Reinforcement Learning (Deep RL) from scratch by Unity Technologies. I thought that the session, led by Arthur Juliani, was extremely informative and wanted to share some big takeaways below.\nIn our conversations with companies, we’ve seen a rise of interesting Deep RL applications, tools and results. In parallel, the inner workings and applications of Deep RL, such as AlphaGo pictured above, can often seem esoteric and hard to understand. In this post, I will give an overview 

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
cv = CountVectorizer(max_df = 0.9, min_df = 2, stop_words='english')

In [8]:
dtm = cv.fit_transform(npr['text'])

In [9]:
dtm

<337x11962 sparse matrix of type '<class 'numpy.int64'>'
	with 156477 stored elements in Compressed Sparse Row format>

In [10]:
from sklearn.decomposition import LatentDirichletAllocation

In [11]:
LDA  = LatentDirichletAllocation(n_components=7, random_state=42)

In [12]:
LDA.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [13]:
# grab the vocabularies of words

In [14]:
len(cv.get_feature_names())

11962

In [15]:
type(cv.get_feature_names())

list

In [16]:
# cv.get_feature_names()[1000]

In [17]:
import random 

In [18]:
random_word_id = random.randint(0,11962)

In [19]:
cv.get_feature_names()[10]

'010'

In [20]:
# grab the topics

In [21]:
len(LDA.components_)

7

In [22]:
type(LDA.components_)

numpy.ndarray

In [23]:
LDA.components_.shape

(7, 11962)

In [24]:
LDA.components_

array([[ 2.14280091, 35.14697724,  0.14285714, ...,  0.14285714,
         0.14285714,  0.14285714],
       [ 0.14291337,  4.42723806,  0.14285714, ...,  0.17533042,
         0.14285714,  0.1750606 ],
       [ 0.14285714, 23.61601879,  4.14285714, ..., 10.34819945,
         2.14285714,  8.30720293],
       ...,
       [ 0.14285714,  8.88069096,  0.14285714, ...,  0.1428592 ,
         0.14285714,  0.14285973],
       [ 0.14285715,  2.44375511,  0.14285715, ...,  0.14285715,
         0.14285715,  0.14285715],
       [ 0.14285714, 67.78666958,  0.14285714, ...,  7.90503846,
         0.14285714,  7.94630424]])

In [25]:
import numpy as np

In [26]:
# ar = np.array([10,200,1])

In [27]:
# ar

In [28]:
# ar.argsort()

In [29]:
single_topic = LDA.components_[0]

In [30]:
single_topic.argsort() #argsort provide index position of sorted values 

array([ 9907, 11930,  4703, ...,  7273,   699,  2906])

In [31]:
single_topic.argsort()[-10:] #grab last 10 values of argsort

array([11388,  6293,  2289,  6393,  6590,  7886, 10855,  7273,   699,
        2906])

In [32]:
top_ten_words = single_topic.argsort()[-20:]

In [33]:
for i in top_ten_words:
    print(cv.get_feature_names()[i])

power
human
intelligence
used
just
model
example
technology
information
world
use
learning
companies
like
machine
people
time
new
ai
data


In [34]:
# grab the higest probablity word per topic

In [35]:
for i,topic in enumerate(LDA.components_):
    print(f" THE TOP 15 WORDS FOR TOPIC #{i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

 THE TOP 15 WORDS FOR TOPIC #0
['model', 'example', 'technology', 'information', 'world', 'use', 'learning', 'companies', 'like', 'machine', 'people', 'time', 'new', 'ai', 'data']




 THE TOP 15 WORDS FOR TOPIC #1
['available', 'weighted', 'star', 'free', 'rating', 'hours', 'average', 'science', 'reviews', 'face', 'python', 'course', 'data', 'machine', 'learning']




 THE TOP 15 WORDS FOR TOPIC #2
['value', 'algorithm', 'function', 'use', 'training', 'time', 'like', 'machine', 'networks', 'model', 'deep', 'neural', 'network', 'data', 'learning']




 THE TOP 15 WORDS FOR TOPIC #3
['just', 'data', 'll', 'use', 'like', 'function', 'learning', 'features', 'input', 'neural', 'output', 'image', 'layer', 'cnn', 'network']




 THE TOP 15 WORDS FOR TOPIC #4
['know', 'think', 'artificial', 'way', 'need', 'make', 'humans', 'people', 'time', 'computer', 'just', 'intelligence', 'like', 'ai', 'human']




 THE TOP 15 WORDS FOR TOPIC #5
['words', 'content', 'got', 'translate', 'language', 'think'

In [36]:
dtm

<337x11962 sparse matrix of type '<class 'numpy.int64'>'
	with 156477 stored elements in Compressed Sparse Row format>

In [99]:
npr

author claps  reading_time  \
0             Justin Lee  8.3K            11   
1            Conor Dewey  1.4K             7   
2       William Koehrsen  2.8K            11   
3           Gant Laborde  1.3K             7   
4       Emmanuel Ameisen   935            11   
..                   ...   ...           ...   
332       Daniel Simmons  3.4K             8   
333  Eugenio Culurciello  2.8K            13   
334           Devin Soni  5.8K             4   
335      Carlos E. Perez  3.9K             7   
336      Nityesh Agarwal  2.4K            13   

                                                  link  \
0    https://medium.com/swlh/chatbots-were-the-next...   
1    https://towardsdatascience.com/python-for-data...   
2    https://towardsdatascience.com/automated-featu...   
3    https://medium.freecodecamp.org/machine-learni...   
4    https://blog.insightdatascience.com/reinforcem...   
..                                                 ...   
332  https://itnext.io/you-can-build-a-neural-netwo...   
333  https://towardsdatascience.com/artificial-inte...   
334  https://towardsdatascience.com/spiking-neural-...   
335  https://medium.com/intuitionmachine/neurons-ar...   
336  https://towardsdatascience.com/wth-does-a-neur...   

                                                 title  \
0    Chatbots were the next big thing: what happene...   
1    Python for Data Science: 8 Concepts You May Ha...   
2    Automated Feature Engineering in Python – Towa...   
3    Machine Learning: how to go from Zero to Hero ...   
4    Reinforcement Learning from scratch – Insight ...   
..                                                 ...   
332  You can build a neural network in JavaScript e...   
333  Artificial Intelligence, AI in 2018 and beyond...   
334  Spiking Neural Networks, the Next Generation o...   
335  Surprise! Neurons are Now More Complex than We...   
336  “WTH does a neural network even learn??” — a n...   

                                                  text  
0    Oh, how the headlines blared:\nChatbots were T...  
1    If you’ve ever found yourself looking up the s...  
2    Machine learning is increasingly moving from h...  
3    If your understanding of A.I. and Machine Lear...  
4    Want to learn about applied Artificial Intelli...  
..                                                 ...  
332  Click here to share this article on LinkedIn »...  
333  These are my opinions on where deep neural net...  
334  Everyone who has been remotely tuned in to rec...  
335  One of the biggest misconceptions around is th...  
336  I believe, we all have that psychologist/philo...  

[337 rows x 6 columns]

In [100]:
topic_results = LDA.transform(dtm)

In [101]:
topic_results.shape

(337, 7)

In [102]:
topic_results[0].argmax()

4

In [103]:
npr['Topic'] = topic_results.argmax(axis=1)

In [104]:
npr

author claps  reading_time  \
0             Justin Lee  8.3K            11   
1            Conor Dewey  1.4K             7   
2       William Koehrsen  2.8K            11   
3           Gant Laborde  1.3K             7   
4       Emmanuel Ameisen   935            11   
..                   ...   ...           ...   
332       Daniel Simmons  3.4K             8   
333  Eugenio Culurciello  2.8K            13   
334           Devin Soni  5.8K             4   
335      Carlos E. Perez  3.9K             7   
336      Nityesh Agarwal  2.4K            13   

                                                  link  \
0    https://medium.com/swlh/chatbots-were-the-next...   
1    https://towardsdatascience.com/python-for-data...   
2    https://towardsdatascience.com/automated-featu...   
3    https://medium.freecodecamp.org/machine-learni...   
4    https://blog.insightdatascience.com/reinforcem...   
..                                                 ...   
332  https://itnext.io/you-can-build-a-neural-netwo...   
333  https://towardsdatascience.com/artificial-inte...   
334  https://towardsdatascience.com/spiking-neural-...   
335  https://medium.com/intuitionmachine/neurons-ar...   
336  https://towardsdatascience.com/wth-does-a-neur...   

                                                 title  \
0    Chatbots were the next big thing: what happene...   
1    Python for Data Science: 8 Concepts You May Ha...   
2    Automated Feature Engineering in Python – Towa...   
3    Machine Learning: how to go from Zero to Hero ...   
4    Reinforcement Learning from scratch – Insight ...   
..                                                 ...   
332  You can build a neural network in JavaScript e...   
333  Artificial Intelligence, AI in 2018 and beyond...   
334  Spiking Neural Networks, the Next Generation o...   
335  Surprise! Neurons are Now More Complex than We...   
336  “WTH does a neural network even learn??” — a n...   

                                                  text  Topic  
0    Oh, how the headlines blared:\nChatbots were T...      4  
1    If you’ve ever found yourself looking up the s...      6  
2    Machine learning is increasingly moving from h...      2  
3    If your understanding of A.I. and Machine Lear...      3  
4    Want to learn about applied Artificial Intelli...      2  
..                                                 ...    ...  
332  Click here to share this article on LinkedIn »...      6  
333  These are my opinions on where deep neural net...      2  
334  Everyone who has been remotely tuned in to rec...      6  
335  One of the biggest misconceptions around is th...      4  
336  I believe, we all have that psychologist/philo...      3  

[337 rows x 7 columns]